### ISSUE TITLE
Is `au run --watch` supported with Electron

### ISSUE THREAD

**Issue by cosminonea** [SmokeHouseProject/applewood#1]
Firstly, I think this is great work. I've been googling around for a while to find a way to integrate all these technologies. So, thanks for doing this!

I am trying to build an Electron app with Aurelia and was wondering if you managed to get Electron to refresh every time the code changes and the app rebuilds.

**Comment by darylcober** [comment]
Hi Cosmin,

 

Short answer is no. However I think it could be done with a gulp task so I believe it is possible.


I do my development using Visual Studio Code and the Aurelia CLI which hosts in Node. I have a Chrome browser open to display the project and it auto-refreshes when I make code changes. Since I only use Electron (currently) to build the desktop app for distribution I did not see a need to integrate a refresh hook. Electron uses a headless Chrome browser to host the solution, so as long as your Desktop Chrome and Electron’s Chrome are the same (or relatively close) version there should (hopefully :)) be no surprises! Obviously I always test my deliverables before I release them, just to make sure everything works ….

 

The Smoke House Project has modified build scripts that push the changed code to the Electron (and Cordova) folders with each change so it is always ready to build with the latest changes. I usually leave a second command prompt open and just run “electron .” to test as I go. It is relatively painless … but it is my personal preference and totally understand if you prefer debugging inside Electron. If I am working on a mobile project, I usually leave XCode or Android Studio open and then just run the project from there in a simulator … Again since the code is auto refreshed I am basically using the other editors as a build mechanism (instead of command line) because it gives me better debugging … hope this all makes sense! :) 

 

I am currently in the process of updating The Smoke House Project (mainly Node and Aurelia core) and am blogging about the process. If you are interested you can find my blog at http://darylcober.blogspot.com 

 

If you want to create a gulp task to refresh electron I would suggest adding another CLI option (maybe –electron) so that it is an option on the command line.

If you are successful and want to contribute your code please feel free to send a pull request!

 

Also, I have been speaking with Rob Eisenberg about accessing the Electron API from inside Aurelia and we may be opening an Aurelia Discourse about this soon so that as a community we might find an elegant solution to this problem and then create official Aurelia documentation about Electron integration with Aurelia. I am hoping we get this happening in the very near future.

 

Please feel free to reach out any time!

 

Happy coding,

Daryl
